### ISSUE TITLE
Support new built-in functions shipped via DMN 1.4 + 1.5

### ISSUE THREAD

**Issue by nikku** [nikku/feelin#32]
__Is your feature request related to a problem? Please describe__

New [built-in functions](https://www.trisotech.com/whats-new-in-dmn-1-4-and-1-5/), including `string join` are not supported yet.

__Describe the solution you'd like__

Latest DMN standard built-ins are supported:

* [x] `string join` (https://github.com/nikku/feelin/pull/35)
* [x] `context put`
* [x] `context merge`
* [x] `context` (https://github.com/nikku/feelin/commit/43c0d0f006cb4431d037ba48ac759176b3bbd1de)
* [x] `now` (https://github.com/nikku/feelin/issues/36)
* [x] `today` (https://github.com/nikku/feelin/issues/36)
* [ ] `round up` (https://github.com/nikku/feelin/issues/40)
* [ ] `round down` (https://github.com/nikku/feelin/issues/40)
* [ ] `round half up` (https://github.com/nikku/feelin/issues/40)
* [ ] `round half down` (https://github.com/nikku/feelin/issues/40)
* [ ] `list replace` (DMN 1.5) (https://github.com/nikku/feelin/issues/39)

__Describe alternatives you've considered__

None.

__Additional context__

None.

**Comment by nikku** [comment]
Closing, as all issues are captured externally.
